### ISSUE TITLE
[1.12.2] Chunk errors

### ISSUE THREAD

**Issue by Tomatobird8** [Earthcomputer/multiconnect#209]
![Chunk error image](https://i.imgur.com/7CMVULi.png)
[pastebin of error message](https://pastebin.com/ddMn1we4)

Server: PaperMC-1.12.2-1618
Client: fabric-loader-0.11.6-1.17.1
Client mods: multiconnect-1.4.8, spark-fabric, fabric-api-0.37.0+1.17, modmenu-2.0.2, cloth-config-5.0.34-fabric

**Comment by Earthcomputer** [comment]
Hi, can you try this again on the latest multiconnect version? I added some debug information to the log which should help me fix the issue.

**Comment by friendlytherapist** [comment]
Same visual errors occur in version 1.4.13. Method of reproducing stays the same. Only errors found in log are as follows and not sure if they are applicable.

`[15:04:32] [Render thread/WARN]: 6 packets for chunk -1, -3 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 4 packets for chunk -1, -1 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 1 packets for chunk -1, -9 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 5 packets for chunk -1, -14 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 9 packets for chunk -1, -17 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 11 packets for chunk -1, -5 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 5 packets for chunk -1, -10 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 4 packets for chunk -1, -16 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 8 packets for chunk -1, -4 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 6 packets for chunk -1, -11 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 14 packets for chunk -1, -12 were dropped due to the chunk not being loaded
[15:04:32] [Render thread/WARN]: 12 packets for chunk -1, -15 were dropped due to the chunk not being loaded
[15:04:33] [Render thread/WARN]: 16 packets for chunk -1, -19 were dropped due to the chunk not being loaded
[15:04:33] [Render thread/WARN]: 22 packets for chunk -1, -21 were dropped due to the chunk not being loaded
[15:04:34] [Render thread/WARN]: 7 packets for chunk -1, -22 were dropped due to the chunk not being loaded
[15:04:36] [Render thread/WARN]: 4 packets for chunk -1, -23 were dropped due to the chunk not being loaded
[15:04:39] [Render thread/WARN]: 25 packets for chunk -1, -7 were dropped due to the chunk not being loaded
[15:04:51] [pool-2-thread-1/WARN]: 40 packets for chunk -1, -6 were dropped due to the chunk not being loaded
[15:04:57] [Render thread/WARN]: 27 packets for chunk -1, -13 were dropped due to the chunk not being loaded
[15:05:51] [pool-2-thread-1/WARN]: 14 packets for chunk -1, -8 were dropped due to the chunk not being loaded
[15:05:51] [pool-2-thread-1/WARN]: 20 packets for chunk -1, -25 were dropped due to the chunk not being loaded
[15:05:51] [pool-2-thread-1/WARN]: 12 packets for chunk -1, -24 were dropped due to the chunk not being loaded
[15:06:02] [Render thread/WARN]: 4 packets for chunk -1, -12 were dropped due to the chunk not being loaded`

**Comment by Earthcomputer** [comment]
Hey sorry about this, can you try again on 1.4.14 and upload your log? I added even more debug information to help with this.

**Comment by friendlytherapist** [comment]
[Hope it helps](https://pastebin.com/CS1w6u4d)

**Comment by friendlytherapist** [comment]
Having trouble uploading to pastebin. Will try posting here.
`[21:59:15] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saved region successfully
[21:59:15] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saved region successfully
[21:59:16] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saved region successfully
[21:59:16] [pool-4-thread-6/INFO]: [STDOUT]: World save took 2031ms
[21:59:20] [Render thread/INFO]: Loaded 26 advancements
[21:59:28] [multiconnect chunk translator #1/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[21:59:28] [multiconnect chunk translator #1/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[21:59:28] [multiconnect chunk translator #1/ERROR]: Minecraft version: 1.17.1
[21:59:28] [multiconnect chunk translator #1/ERROR]: multiconnect version: 1.4.14
[21:59:28] [multiconnect chunk translator #1/ERROR]: Server version: 340 (1.12.2)
[21:59:28] [multiconnect chunk translator #1/ERROR]: Server brand: vanilla
[21:59:28] [multiconnect chunk translator #1/ERROR]: Chunk pos: 322, 495
[21:59:28] [multiconnect chunk translator #1/ERROR]: Vertical strip bitmask: [4]
[21:59:28] [multiconnect chunk translator #1/ERROR]: Compressed packet data: H4sIAAAAAAAA/+2Wz2sTQRTH31sNjlZkGulVkvYUvVgoHvQSBiyxgkgQkT110YOQiwf1nMStqOQQtRUUD71EEBKptXv34j0H2YoXi3+Bf4Lvx26brVFESuthH/S70zffnfeZ2bfbFk6BnWp6Jyd/4FN8hc+wi0N8jC+xhW18gM8xxGV8gku4gg/xBTbx6vDY1qFV89GzobNtexemRY3bAEDjbCjahJgUIN4AHvNcYO6thmXjyEJqO6IkZkETNkkk6dQXhmHic7/6ui32dVtnKaHKvkmT+AAIoXykSmrcfWAlPhC+b6ZGaQoHcKRKV3JDk1ad47Fhn8QQdmI4pz5ZGlI+xQFV4LpfzjFf4mBlMivKPuKjstt8osadOzXCR2vwrcJnS3Jl3w6fO7yXfEb4Mj5VXm/Lycndtdt8NZobsr28BZbUEJmn6wkfCh8iHSjxVUFY7Z3ScA5/IPlmZemzv+WLN2QlL8OX9WkfgJ6F8LmEz7a1U5iBfoqqtq39kvZONeyUy95IX02KzlLWzM/ycD7LN7b/Mn06xqd8NQCPfE7JbLafVYupVpTS4/VK/1z3r3xdIaNnVXO29ekNGze+264NX9dv0pk9ucK6m+/SV3p1Wxco2wluj6nbCfaKb50PishUqSGLrOuW9YNtGVZmAiULtDqcYMUh852X58udPG3l+do95Tt+U4a3Mi/M+44qP/n1yUXKwhJrGLCD+KDN4yLzeVfkK3ONtW1V+W7WklNN62pvT9wgvqWGv7kGMOHFUZOym1Ff5gaL4vDFTb6oP44v6u/wRQMmuyia1k21SnXBEz6pHv6Br7TNJ/tYWvSYD8bygfL58VphEAhZkOErDET7TWDlG+l2GHnxjTDUpvp6LiXL6sn5VYWs+vvzeyR8tB6+o+W3oBBSFleVvTny9S0Re2HQGOEzzpPPDvMZ0uAoaR+FD8f0S8qX9IuVvrI85L+aPNfO9JWzqtoHsEb7uAHALyCsgTiaUsbpMSifH0eDhqofqxYGqg2ftD9Bc5Hobl80SG73zXVN2CRRFjWO0sHuvp+WfUwb+dKP5Use07E4Wqks1Jd7lQXV+orqSkV1oU565jTN9US3fcuqvUpye93/rInorSYaon5M6cuj+0i2F0VjzyXj65dp070s3y91k3TvIHwN2vT/zMfDizP6T8dcUa8l1KuF/Ym07kxSN/kVcJ/qH1TdNA6qbhoHVTePPPLII4888sgjjzzyyCOP/Y2fByOkLDoaAAA=
[21:59:28] [multiconnect chunk translator #1/ERROR]: Failed to translate chunk 322, 495
java.lang.IndexOutOfBoundsException: readerIndex(6714) + length(1) exceeds writerIndex(6714): UnpooledHeapByteBuf(ridx: 6714, widx: 6714, cap: 6714/6714)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByte$21(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:248) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:189) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByte(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.lambda$registerTranslators$0(Protocol_1_12_2.java:155) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:119) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:98) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:115) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:218) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:225) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[21:59:33] [multiconnect chunk translator #0/ERROR]: Failed to translate chunk 327, 498
java.lang.IndexOutOfBoundsException: readerIndex(6168) + length(1) exceeds writerIndex(6168): UnpooledHeapByteBuf(ridx: 6168, widx: 6168, cap: 6168/6168)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByte$21(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:248) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:189) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByte(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.lambda$registerTranslators$0(Protocol_1_12_2.java:155) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:119) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:98) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:115) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:218) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:225) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[21:59:44] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saving region 10,14 to disk /Users/mkrone/Desktop/Evan/-MC/MultiMC.app/Contents/MacOS/instances/comet tweaks test multi/.minecraft/baritone/192.168.2.197:53874/cache
[21:59:44] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saving region 9,14 to disk /Users/mkrone/Desktop/Evan/-MC/MultiMC.app/Contents/MacOS/instances/comet tweaks test multi/.minecraft/baritone/192.168.2.197:53874/cache
[21:59:44] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saving region 9,15 to disk /Users/mkrone/Desktop/Evan/-MC/MultiMC.app/Contents/MacOS/instances/comet tweaks test multi/.minecraft/baritone/192.168.2.197:53874/cache
[21:59:44] [pool-4-thread-8/INFO]: [STDOUT]: Saving region 10,15 to disk /Users/mkrone/Desktop/Evan/-MC/MultiMC.app/Contents/MacOS/instances/comet tweaks test multi/.minecraft/baritone/192.168.2.197:53874/cache
[21:59:44] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saved region successfully
[21:59:44] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saved region successfully
[21:59:44] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saved region successfully
[21:59:44] [pool-4-thread-8/INFO]: [STDOUT]: Saved region successfully
[21:59:44] [pool-4-thread-8/INFO]: [STDOUT]: World save took 158ms
[21:59:48] [multiconnect chunk translator #2/ERROR]: Failed to translate chunk 312, 495
java.lang.IndexOutOfBoundsException: readerIndex(6173) + length(1) exceeds writerIndex(6173): UnpooledHeapByteBuf(ridx: 6173, widx: 6173, cap: 6173/6173)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByte$21(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:248) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:189) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByte(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.lambda$registerTranslators$0(Protocol_1_12_2.java:155) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:119) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:98) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:115) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:218) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:225) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[21:59:59] [multiconnect chunk translator #0/ERROR]: Failed to translate chunk 291, 476
java.lang.IndexOutOfBoundsException: readerIndex(6172) + length(1) exceeds writerIndex(6172): UnpooledHeapByteBuf(ridx: 6172, widx: 6172, cap: 6172/6172)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByte$21(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:248) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:189) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByte(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.lambda$registerTranslators$0(Protocol_1_12_2.java:155) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:119) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:98) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:115) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:218) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:225) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[22:00:07] [multiconnect chunk translator #0/ERROR]: Failed to translate chunk 290, 455
java.lang.IndexOutOfBoundsException: readerIndex(12872) + length(1) exceeds writerIndex(12872): UnpooledHeapByteBuf(ridx: 12872, widx: 12872, cap: 12872/12872)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByte$21(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:248) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:189) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByte(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.lambda$registerTranslators$0(Protocol_1_12_2.java:155) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:119) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:98) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:115) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:218) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:225) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[22:00:24] [Render thread/WARN]: RenderChunk{chunkX=248, chunkY=3, chunkZ=464} changed update type to IMPORTANT_REBUILD while in queue for REBUILD, skipping
[22:00:24] [multiconnect chunk translator #0/ERROR]: Failed to translate chunk 250, 469
java.lang.IndexOutOfBoundsException: readerIndex(19543) + length(1) exceeds writerIndex(19543): UnpooledHeapByteBuf(ridx: 19543, widx: 19543, cap: 19543/19543)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByte$21(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:248) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:189) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByte(TransformerByteBuf.java:773) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.lambda$registerTranslators$0(Protocol_1_12_2.java:155) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:119) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:98) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:115) ~[multiconnect-1.4.14.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:218) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:225) [multiconnect-1.4.14.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[22:00:26] [Render thread/WARN]: RenderChunk{chunkX=250, chunkY=3, chunkZ=471} changed update type to IMPORTANT_REBUILD while in queue for REBUILD, skipping`

**Comment by friendlytherapist** [comment]
[Hope it helps](https://textbin.net/uctut31atq)

**Comment by Earthcomputer** [comment]
This should hopefully fixed in 1.4.15, please let me know if not (with an updated log) and I'll reopen.

**Comment by friendlytherapist** [comment]
Unfortunately 1.4.15 version does not fix the visual errors. Using 100% fresh multimc installs joining 100% vanilla 1.12.2 localhost from the 1.4.15 version in 1.17.1. Errors in log are only these:

`[16:01:12] [ForkJoinPool-1-worker-7/WARN]: The mod "multiconnect" contains invalid entries in its mod json:
- Unsupported root entry "__comment__" at line 42 column 16
[16:10:03] [Render thread/WARN]: 6 packets for chunk -1, -20 were dropped due to the chunk not being loaded
[16:10:05] [Render thread/WARN]: 59 packets for chunk -1, -21 were dropped due to the chunk not being loaded
[16:10:10] [Render thread/WARN]: 94 packets for chunk -1, -4 were dropped due to the chunk not being loaded
[16:10:12] [Render thread/WARN]: 40 packets for chunk -1, -18 were dropped due to the chunk not being loaded
[16:10:35] [Render thread/WARN]: 40 packets for chunk -1, -17 were dropped due to the chunk not being loaded
[16:10:48] [Render thread/WARN]: 87 packets for chunk -1, -15 were dropped due to the chunk not being loaded
[16:10:57] [Render thread/WARN]: 57 packets for chunk -1, -14 were dropped due to the chunk not being loaded
[16:11:24] [Render thread/WARN]: 380 packets for chunk -1, -11 were dropped due to the chunk not being loaded
[16:11:38] [Render thread/WARN]: 146 packets for chunk -1, -10 were dropped due to the chunk not being loaded
[16:11:44] [Render thread/WARN]: 134 packets for chunk -1, -13 were dropped due to the chunk not being loaded
[16:11:54] [Render thread/WARN]: 241 packets for chunk -1, -12 were dropped due to the chunk not being loaded
[16:13:07] [Render thread/WARN]: 5 packets for chunk -1, -12 were dropped due to the chunk not being loaded`

**Comment by Earthcomputer** [comment]
Please can you paste your whole log?

**Comment by friendlytherapist** [comment]
[Full log](https://textbin.net/ktwa8kj3r3)

**Comment by Earthcomputer** [comment]
I haven't been able to reproduce this issue. Is there a server I can join where it's reliably reproducible?

**Comment by friendlytherapist** [comment]
Yes, just generate new chunks on 2b2t.org

**Comment by Earthcomputer** [comment]
I am not joining that server. Is there another server I can join with the same issue?

**Comment by friendlytherapist** [comment]
I will look for 1.12.2 servers to join and test. Though it is difficult to find a survival server and go far enough out to gen new chunks. The easiest option is loading up a lan server and joining on an alt which is what ive been using to test the newest versions. Ill see if I can reproduce the issue on another server other than 2b2t.org or localhost.

**Comment by Earthcomputer** [comment]
As long as you're sure you can reliably reproduce it by generating new chunks that's good enough for me. I have a local test server.

**Comment by friendlytherapist** [comment]
The issue is only when generating new chunks. A re-log fixes the visual glitches and running back through the previously generated terrain, you will find no glitches where they were before. But generating new terrain will produce them. Using f3 to reload chunks does not fix the errors. Walking into the glitched terrain will glitch out the player. Placing blocks in the glitched terrain will replace the air with the proper block but only where the new block was placed. As far as I can tell they occur more in oceans and on the nether roof. Although im not sure if they are just more easy to notice there.

**Comment by friendlytherapist** [comment]
[I have uploaded a video showing the glitches if you still cant reproduce them.](https://www.youtube.com/watch?v=NbNulhEEfd4)

**Comment by Felix14-v2** [comment]
Sometimes I have the same problem, but not with new chunks: [[Demo 1]](https://youtu.be/KwhG8Gm1OV0) [[Demo 2]](https://youtu.be/q2KtSNtBF1g) [[Demo 3]](https://youtu.be/DhADvOUVu50)

Demo 1: [2021-09-02-3.log](https://github.com/Earthcomputer/multiconnect/files/7098882/2021-09-02-3.log) (nothing interesting)
Demo 2-3: [2021-09-02-2.log](https://github.com/Earthcomputer/multiconnect/files/7098978/2021-09-02-2.log)
Demo video time:
2) 13:52:14-13:54:07 (there are also spam an errors with the arrows owners data)
3) 13:45:50-13:46:31 (packets for chunks were dropped)

**Comment by friendlytherapist** [comment]
Is there a chance of this being fixed? do you need more information? I currently cant play because of these visual glitches.

**Comment by Earthcomputer** [comment]
I've been busy, I'll take a look today.

**Comment by Earthcomputer** [comment]
I still can't reproduce this issue on a vanilla server

**Comment by Earthcomputer** [comment]
Perhaps it's a conflict with another mod you have installed. Could you verify this still happens with just multiconnect, and if so, let me know which mod it's conflicting with?
I did notice that you said "100% fresh multimc install" but I'm not sure what that exactly means in terms of what mods you have loaded.

**Comment by friendlytherapist** [comment]
Hi i just went through again and verified that it still occurs. I even tested on a different computer and they still occur.

- Using the multimc app
- Java 16
- Creating new 1.17.1 instance and installing fabric from multimc menu
- Only mod installed is newest Multimc (not even fabric api is installed)
- Creating new 1.12.2 instance
- Joining 1.12 from 1.17 through localhost
- Only errors are "[17:10:35] [Render thread/WARN]: 40 packets for chunk -1, -17 were dropped due to the chunk not being loaded"

**Comment by Sneakometer** [comment]
@friendlytherapist your logs say that your are still running multiconnect 1.4.14. Could you please verify that this issue is present on latest multiconnect too?

**Comment by friendlytherapist** [comment]
[Heres a log I just made. No packets for chunk errors occurred this time though.](https://pastebin.com/1N0jRryj) My above message applies to this log.

**Comment by Felix14-v2** [comment]
> I still can't reproduce this issue on a vanilla server

@Earthcomputer , I think this way of reproducing can help: [[Demo]](https://youtu.be/ErDlo5pJ6EE)

**Comment by Earthcomputer** [comment]
Thanks for that! I will try that when I get the chance

**Comment by friendlytherapist** [comment]
@Earthcomputer Ill just clarify that I was running the localhost 1.12.2 server on one computer and the 1.17.1 multiconnect client on another computer and it still occurs. I dont think localhost causes it because it still happens on 1.12.2 servers like 2b2t.org

**Comment by Earthcomputer** [comment]
$20 bounty for fixing this one :)

**Comment by Felix14-v2** [comment]
> [[Demo 2]](https://youtu.be/q2KtSNtBF1g) – errors in updating TNT blocks
[[Demo 3]](https://youtu.be/DhADvOUVu50) – yellow terracotta is not displayed

Demo 1: [2021-09-02-3.log](https://github.com/Earthcomputer/multiconnect/files/7098882/2021-09-02-3.log) (nothing interesting)
Demo 2-3: [2021-09-02-2.log](https://github.com/Earthcomputer/multiconnect/files/7098978/2021-09-02-2.log)

@Earthcomputer , problems with block updates are still present. Should I create a separate bug report for them?

**Comment by friendlytherapist** [comment]
So I just tested the newest version and the chunk vanishing seems to be fixed! But unfortunately that is the only thing that was fixed. In issue #257 I tested beds, liquids, tnt and falling sand and they all do not work as intended (same issues as the bug report).
