### ISSUE TITLE
[1.17.1] -> [1.12.2] Unable to join server, dropping chunk packets too far away from render distance center

### ISSUE THREAD

**Issue by Nessiesson** [Earthcomputer/multiconnect#211]
I left a server after teleporting to a random location and flying around for a bit. A bit later when I wanted to join the server again, the game froze on the "Loading terrain..." screen, ultimately disconnecting. Attached is a logfile of opening the client and attempting to join the server.

[latest.log](https://github.com/Earthcomputer/multiconnect/files/6904120/latest.log)

**Comment by Earthcomputer** [comment]
Weird, seems to only be happening in that location on the dugged creative server, I'll investigate

**Comment by Earthcomputer** [comment]
I've fixed the chunk packets being dropped, in terms of the disconnect, that looks like a timeout, and will likely be fixed by optimizing the chunk translator. That location you were disconnecting at has a lot of subchunks to translate. As a workaround for now, try decreasing your client render distance.

**Comment by Nessiesson** [comment]
Thank you for looking into this! Unfortunately, it seems to not been sufficient as I am still unable to join, even at render distance 2. :/ At least it doesn't spam dropped chunk warnings in the logfile anymore.

**Comment by Earthcomputer** [comment]
Ah, this is going to be a fun optimization issue. I'll do some profiling tomorrow to see what can be done about it

**Comment by Felix14-v2** [comment]
@Earthcomputer , it looks like this issue is back in 1.19, but this time it is `Ignoring chunk since it's not in the view range`: 
https://youtu.be/hHmpCYGp1_s

Unfortunately, I can't upload the logs, because GitHub gives me an error, Mediafire swears at the virus in it, and other methods don't work either 0_0
I'll do it as soon as I get back to the computer.

**Comment by Felix14-v2** [comment]
UPD: Can't reproduce this from the desktop Java Edition, this is probably a problem on the PoJav part.
